version: '3.8'

services:
  flask-app:
    build:
      context: .
    ports:
      - "5001:5000"
    env_file:
      - .env.local
    environment:
      FLASK_ENV: development
    command: ["python3", "-m", "flask", "run", "--host=0.0.0.0"]
